/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hotel_Management_System;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jerry Vu
 */
public class Hotel_System extends javax.swing.JFrame {

    /**
     * Creates new form Hotel_System
     */
    public Hotel_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtCustomerRef = new javax.swing.JTextField();
        jtxtAddress = new javax.swing.JTextField();
        jtxtLastname = new javax.swing.JTextField();
        jtxtZipCode = new javax.swing.JTextField();
        jtxtEmail = new javax.swing.JTextField();
        jtxtPhoneNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JButton();
        jtxtTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jbtnTotalCost = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jCobRmNo = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCobMeal = new javax.swing.JComboBox<>();
        jCobRmType = new javax.swing.JComboBox<>();
        jCobGender = new javax.swing.JComboBox<>();
        jbtnDelete = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Firstname:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Customer_Ref:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Lastname:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Zip Code:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Meal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Phone Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, -1));

        jtxtCustomerRef.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtCustomerRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 140, -1));

        jtxtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, -1));

        jtxtLastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, -1));

        jtxtZipCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, -1));

        jtxtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 140, -1));

        jtxtPhoneNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Date of Birth:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Nationality:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ID Type:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Gender:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Check Out Date:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Check In Date:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Room Type:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Total:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));
        getContentPane().add(jLocaleChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer_Ref", "Firstname", "Lastname", "Address", "Zip Code", "Phone Number", "Email", "Nationality", "Date of Birth", "Gender", "Check In Date", "Check Out Date", "Meal", "Room Type", "Room No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 720, 490));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 140, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 140, -1));
        getContentPane().add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 140, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Room No:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Tax:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("SubTotal:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 140, -1));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 140, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 140, -1));

        jbtnTotalCost.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnTotalCost.setText("Total Cost");
        jbtnTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalCostActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 550, -1, -1));

        jCobRmNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCobRmNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room No.", "001", "002", "003", "004", "005", "006", "007", "008", "009", "010" }));
        getContentPane().add(jCobRmNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 140, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ID Type", "Drivers ID", "Passport", "Student ID" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, -1));

        jCobMeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCobMeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select No. of Meal", "1", "2", "3" }));
        getContentPane().add(jCobMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 140, -1));

        jCobRmType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCobRmType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room Type", "Single", "Double" }));
        getContentPane().add(jCobRmType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 140, -1));

        jCobGender.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCobGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        getContentPane().add(jCobGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 140, -1));

        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, -1, -1));

        jbtnUpdate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Hotel Management System", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jbtnTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalCostActionPerformed
        int SingleRoom = 40;
        int DoubleRoom = 75;
        int FamilyRoom = 115;
        
        int oneMeal = 9;
        int twoMeals = 15;
        int threeMeals = 23;
        SimpleDateFormat format = new SimpleDateFormat ("yyyy-MM-dd");
        Date Check_In_Date = null;
        Date Check_Out_Date = null;
        
        try{
            Check_In_Date = format.parse(format.format(jDateChooser3.getDate()));
            Check_Out_Date = format.parse(format.format(jDateChooser2.getDate()));
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        long Checkdiff = Check_In_Date.getTime() - Check_Out_Date.getTime();
        int Daysdiff = (int)(Checkdiff / 1000/60/60/24);
        
        if (jCobRmType.getSelectedItem().equals("Single") && jCobMeal.getSelectedItem().equals("1"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        else if (jCobRmType.getSelectedItem().equals("Double") && jCobMeal.getSelectedItem().equals("1"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        else if (jCobRmType.getSelectedItem().equals("Family") && jCobMeal.getSelectedItem().equals("1"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        if (jCobRmType.getSelectedItem().equals("Single") && jCobMeal.getSelectedItem().equals("2"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        else if (jCobRmType.getSelectedItem().equals("Double") && jCobMeal.getSelectedItem().equals("2"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        else if (jCobRmType.getSelectedItem().equals("Family") && jCobMeal.getSelectedItem().equals("2"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        if (jCobRmType.getSelectedItem().equals("Single") && jCobMeal.getSelectedItem().equals("3"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        else if (jCobRmType.getSelectedItem().equals("Double") && jCobMeal.getSelectedItem().equals("3"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        else if (jCobRmType.getSelectedItem().equals("Family") && jCobMeal.getSelectedItem().equals("3"))
        {
            jtxtTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtTax.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
            jtxtSubTotal.setText(Integer.toString(Daysdiff * SingleRoom) + oneMeal);
        
            double q = Double.parseDouble(jtxtTax.getText());
            q = (q * 0.25)/ 100;
            String tax = String.format("$ %.2f", q);
            jtxtTax.setText(tax);
            
            double st = Double.parseDouble(jtxtSubTotal.getText());
            String subtotal = String.format("$ %.2f", st);
            jtxtSubTotal.setText(subtotal);
            
            double tt = Double.parseDouble(jtxtTotal.getText());
            String total = String.format("$ %.2f", tt + q);
            jtxtTotal.setText(total);
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{
        
        jtxtCustomerRef.getText(),
        jtxtFirstname.getText(),
        jtxtLastname.getText(),
        jtxtAddress.getText(),
        jtxtZipCode.getText(),
        jtxtPhoneNumber.getText(),
        jtxtEmail.getText(),
        jLocaleChooser1.getSelectedItem(),
        jDateChooser1.getDate(),
        jCobRmType.getSelectedItem(),
        jCobGender.getSelectedItem(),
        jDateChooser2.getDate(),
        jDateChooser3.getDate(),
        jCobMeal.getSelectedItem(),
        jCobRmNo.getSelectedItem(),
        });
    }//GEN-LAST:event_jbtnTotalCostActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1){
            if (jTable1.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Hotel Booking Update confirmed", "Hotel Management System",
                JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1){
            if (jTable1.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Hotel Booking Update confirmed", "Hotel Management System",
                JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        jtxtCustomerRef.setText(null);
        jtxtFirstname.setText(null);
        jtxtLastname.setText(null);
        jtxtAddress.setText(null);
        jtxtEmail.setText(null);
        jtxtZipCode.setText(null);
        jtxtPhoneNumber.setText(null);
        jtxtTax.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
        jDateChooser1.setDate(null);
        jDateChooser2.setDate(null);
        jDateChooser3.setDate(null);
        jCobMeal.setSelectedIndex(0);
        jCobRmType.setSelectedIndex(0);
        jCobRmNo.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCobGender;
    private javax.swing.JComboBox<String> jCobMeal;
    private javax.swing.JComboBox<String> jCobRmNo;
    private javax.swing.JComboBox<String> jCobRmType;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotalCost;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCustomerRef;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLastname;
    private javax.swing.JTextField jtxtPhoneNumber;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtZipCode;
    // End of variables declaration//GEN-END:variables
}
